from . import ir_attachment
from . import company_trade_license_number
from . import res_company
from . import res_partner_type
from . import res_partner
from . import crm_lead
from . import crm_tag
from . import crm_type
from . import cost_revenue_dist
from . import crm_competitor_reason
from . import crm_lost_reason
from . import opportunity_region
from . import sale_order
from . import sale_order_line
from . import quotation_type
from . import res_config_settings
from . import crm_lead_forecast_category
from . import crm_stage
from . import opportunity_classification
from . import key_account
from . import sale_order_approval_history
