{
    'name': 'ebs Custom Opportunity',
    "version": "14.0.2.2.5",
    'depends': [
        'contacts',
        'sale',
        'sale_crm',
        'sale_margin',
        'sale_stock',
        'account',
        'account_followup',
        'stock_landed_costs',
        'web_notify',
        'ebs_analytic_account',
        'account_payment_term_is_advanced',
        'product_description',
        'product_main_supplier',
        'product_classification',
        'web_m2x_options',
        'product_part_number',
        'product_origin',
        'base_company_customization_flag',
        'partner_phone_extension',
        'base_dynamic_approval',
    ],

    'category': 'crm',
    'data': [
        'security/access_rules.xml',
        'security/ir.model.access.csv',
        'wizards/crm_lead_lost.xml',
        'views/crm_lead.xml',
        'views/crm_tag.xml',
        'views/opportunity_region.xml',
        'views/crm_lost_reason.xml',
        'views/key_account.xml',
        'views/res_partner.xml',
        'views/opportunity_classification.xml',
        'views/crm_lead_forecast_category.xml',
        'views/crm_type.xml',
        'views/crm_competitor_reason.xml',
        'data/ir_sequence.xml',
        'data/opportunity_classification.xml',
        'views/sale_order.xml',
        'views/quotation_type.xml',
        'views/cost_revenue_dist.xml',
        'views/crm_stage.xml',
        'views/res_partner_type.xml',
        'views/res_config_settings.xml',
        'data/crm_stage.xml',
        'data/key_account.xml',
        'data/ir_config_parameter.xml',
        'data/res_partner_type.xml',
        'data/sale_order.xml',
        'wizards/import_sale_order_line_wizard.xml',
        'views/sale_order_approval_history_views.xml',
        'views/res_company.xml',
        'views/res_partner_filter.xml',
    ]
}
